
name: Deploy to Dokku

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    
    steps:
    - uses: actions/checkout@v2
        
    - name: copy config file
      run: |
        echo "SECRET_THING" > config.json
        git config user.name zhalmakh
        git config user.email "birc4n.serkan@yandex.com"
        git add .
        git commit -m "update"
    - name: Deploy
      uses: fasetto/dokku-deploy@master
      with:
        dokku-deploy-key: ${{ secrets.DOKKU_DEPLOY_KEY }}
        dokku-host: "dokku.fabyo.net"
        dokku-app: "zhalmakh"
