
name: Deploy to Dokku

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: testing
      run: |
        echo "SECRET_FILE" > config.json
        git config user.name fasetto
        git config user.email "birc4n.serkan@yandex.com"
        git add .
        git commit -m "add config"

    - name: deploy
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
        ssh-private-key: ${{ secrets.DOKKU_DEPLOY_KEY }}
        dokku-host: "dokku.fabyo.net"
        app-name: "zhalmakh"
 
